// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlite

import (
	"github.com/mozey/ft"
)

type Account struct {
	AccountID string `db:"account_id"`
	Descr     string `db:"descr"`
}

type AccountXUser struct {
	AccountID string `db:"account_id"`
	UserID    string `db:"user_id"`
}

type Addr struct {
	Hash     string `db:"hash"`
	Taxonomy string `db:"taxonomy"`
	Val      string `db:"val"`
	Mod      string `db:"mod"`
}

type Addrtype struct {
	Type string `db:"type"`
}

type Cat struct {
	SKU   string `db:"sku"`
	Title string `db:"title"`
	Descr string `db:"descr"`
	State string `db:"state"`
	Mod   string `db:"mod"`
	ModID string `db:"mod_id"`
}

type CatConfig struct {
	SKU  string `db:"sku"`
	Term string `db:"term"`
	Val  string `db:"val"`
}

type CatImg struct {
	SKU   string `db:"sku"`
	Hash  string `db:"hash"`
	Descr string `db:"descr"`
	Idx   int64  `db:"idx"`
}

type CatPrice struct {
	SKU   string `db:"sku"`
	Price int64  `db:"price"`
}

type CatQty struct {
	SKU   string `db:"sku"`
	Depot string `db:"depot"`
	Qty   int64  `db:"qty"`
}

type CatState struct {
	State  string `db:"state"`
	Custom string `db:"custom"`
}

type CatTag struct {
	SKU string `db:"sku"`
	Tag string `db:"tag"`
}

type Config struct {
	Term string `db:"term"`
	Val  string `db:"val"`
	Mod  string `db:"mod"`
}

type Discount struct {
	DiscountID string `db:"discount_id"`
	Pct        int64  `db:"pct"`
	Discount   int64  `db:"discount"`
	Descr      string `db:"descr"`
	Mod        string `db:"mod"`
	ModID      string `db:"mod_id"`
}

type DiscountCountry struct {
	DiscountID string `db:"discount_id"`
	Country    string `db:"country"`
}

type DiscountOpt struct {
	DiscountID string `db:"discount_id"`
}

type DiscountRange struct {
	DiscountID string `db:"discount_id"`
	Start      string `db:"start"`
	End        string `db:"end"`
}

type DiscountSku struct {
	DiscountID string `db:"discount_id"`
	SKU        string `db:"sku"`
}

type DiscountTag struct {
	DiscountID string `db:"discount_id"`
	Tag        string `db:"tag"`
}

type DiscountUser struct {
	DiscountID string `db:"discount_id"`
	UserID     string `db:"user_id"`
}

type Eltag struct {
	Eltag string `db:"eltag"`
}

type Eltype struct {
	Eltype string `db:"eltype"`
}

type Field struct {
	Term   string `db:"term"`
	Deflt  string `db:"deflt"`
	Eltag  string `db:"eltag"`
	Eltype string `db:"eltype"`
	Elreq  int64  `db:"elreq"`
	Idx    int64  `db:"idx"`
	Mod    string `db:"mod"`
	ModID  string `db:"mod_id"`
}

type FieldElattr struct {
	Term   string `db:"term"`
	Elattr string `db:"elattr"`
	Val    string `db:"val"`
}

type FieldOpt struct {
	Term  string `db:"term"`
	Val   string `db:"val"`
	Descr string `db:"descr"`
}

type Img struct {
	Hash string `db:"hash"`
	Ext  string `db:"ext"`
	Alt  string `db:"alt"`
	Mod  string `db:"mod"`
}

type OrderAct struct {
	OrderID     string `db:"order_id"`
	OrderLineID string `db:"order_line_id"`
	State       string `db:"state"`
	Msg         string `db:"msg"`
	UserID      string `db:"user_id"`
	Admin       int64  `db:"admin"`
	Mod         string `db:"mod"`
}

type OrderAddr struct {
	OrderID string `db:"order_id"`
	Type    string `db:"type"`
	Hash    string `db:"hash"`
}

type OrderConfig struct {
	OrderID     string `db:"order_id"`
	OrderLineID string `db:"order_line_id"`
	Term        string `db:"term"`
	Val         string `db:"val"`
}

type OrderLine struct {
	OrderLineID string `db:"order_line_id"`
	OrderID     string `db:"order_id"`
	State       string `db:"state"`
	SKU         string `db:"sku"`
	Price       int64  `db:"price"`
	Qty         int64  `db:"qty"`
}

type OrderState struct {
	State string `db:"state"`
}

type OrderTag struct {
	OrderID     string `db:"order_id"`
	OrderLineID string `db:"order_line_id"`
	Tag         string `db:"tag"`
}

type OrderTax struct {
	OrderID     string  `db:"order_id"`
	OrderLineID string  `db:"order_line_id"`
	Fixed       int64   `db:"fixed"`
	Tax         float64 `db:"tax"`
	Pct         int64   `db:"pct"`
	Mod         string  `db:"mod"`
}

type OrderTran struct {
	OrderID string `db:"order_id"`
	TranID  string `db:"tran_id"`
}

type Orders struct {
	OrderID string `db:"order_id"`
	OrderNo string `db:"order_no"`
	State   string `db:"state"`
	Notes   string `db:"notes"`
	UserID  string `db:"user_id"`
	Paid    int64  `db:"paid"`
	Mod     string `db:"mod"`
	ModID   string `db:"mod_id"`
}

type Role struct {
	Role string `db:"role"`
}

type RolePerm struct {
	Role string `db:"role"`
	Perm string `db:"perm"`
	Path string `db:"path"`
}

type Session struct {
	UserID   string `db:"user_id"`
	Otp      string `db:"otp"`
	Verified int64  `db:"verified"`
	Attempts int64  `db:"attempts"`
	Mod      string `db:"mod"`
}

type SessionAct struct {
	UserID string `db:"user_id"`
	Msg    string `db:"msg"`
	Mod    string `db:"mod"`
}

type Tag struct {
	Tag string `db:"tag"`
	Mod string `db:"mod"`
}

type Tax struct {
	Country string `db:"country"`
	Tag     string `db:"tag"`
	SKU     string `db:"sku"`
	Vat     int64  `db:"vat"`
	Pct     int64  `db:"pct"`
	Tax     int64  `db:"tax"`
	Descr   string `db:"descr"`
	Mod     string `db:"mod"`
	ModID   string `db:"mod_id"`
}

type Taxonomy struct {
	Taxonomy string `db:"taxonomy"`
	Descr    string `db:"descr"`
	Mod      string `db:"mod"`
}

type TaxonomyXTerm struct {
	Taxonomy ft.NString `db:"taxonomy"`
	Term     ft.NString `db:"term"`
}

type Term struct {
	Term  string `db:"term"`
	Descr string `db:"descr"`
	Mod   string `db:"mod"`
}

type TermAttr struct {
	Term string `db:"term"`
	Attr string `db:"attr"`
}

type TermTree struct {
	Term   string `db:"term"`
	Parent string `db:"parent"`
}

type Tran struct {
	TranID    string `db:"tran_id"`
	AccountID string `db:"account_id"`
	State     string `db:"state"`
	Descr     string `db:"descr"`
	Amount    int64  `db:"amount"`
	Currency  string `db:"currency"`
	UserID    string `db:"user_id"`
	Mod       string `db:"mod"`
}

type TranConfig struct {
	TranID string `db:"tran_id"`
	Term   string `db:"term"`
	Val    string `db:"val"`
	UserID string `db:"user_id"`
}

type TranTag struct {
	TranID string `db:"tran_id"`
	Tag    string `db:"tag"`
}

type User struct {
	UserID   string `db:"user_id"`
	Email    string `db:"email"`
	Username string `db:"username"`
	Descr    string `db:"descr"`
	Role     string `db:"role"`
	Verified int64  `db:"verified"`
	Disabled int64  `db:"disabled"`
	Mod      string `db:"mod"`
}

type UserConfig struct {
	UserID string `db:"user_id"`
	Term   string `db:"term"`
	Val    string `db:"val"`
}

type UserTag struct {
	UserID string `db:"user_id"`
	Tag    string `db:"tag"`
}

type Variant struct {
	GroupID string `db:"group_id"`
	SKU     string `db:"sku"`
	Idx     int64  `db:"idx"`
}

type Vat struct {
	Country string `db:"country"`
	Pct     int64  `db:"pct"`
	Mod     string `db:"mod"`
	ModID   string `db:"mod_id"`
}
