// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlite

import (
	"context"
)

type Querier interface {
	// SessionByUserID fetches a single row
	SessionByUserID(ctx context.Context, userID string) (SessionByUserIDRow, error)
}

var _ Querier = (*Queries)(nil)
